version: "3"
services:
  api:
    build: api/
    container_name: api
    image: api
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: >
      --requirepass redis

networks:
  default:
    external:
      name: api
